//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECouponAPI.Models
{
    using System;

    public partial class COUPON
    {
        public int id { get; set; }
        public int COUPONGROUPID { get; set; }
        public string CODE { get; set; }
        public string COUPONTYPECODE { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public Nullable<int> PAYMENT_ID { get; set; }
        public Nullable<int> MEMBER_ID { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string TELNO { get; set; }
        public string MOBILENO { get; set; }
        public string PACKAGE_CODE { get; set; }
        public string PACKAGE_NAME { get; set; }
        public string CHECKLIST_TH { get; set; }
        public string CHECKLIST_EN { get; set; }
        public string TERMOFUSE_TH { get; set; }
        public string TERMOFUSE_EN { get; set; }
        public Nullable<System.DateTime> DATE_PURCHASED { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> DATE_EXPIRED { get; set; }
        public Nullable<System.DateTime> GENERATED_DATE { get; set; }
        public Nullable<System.DateTime> PRINTED_DATETIME { get; set; }
        public string PRINTED_BY { get; set; }
        public Nullable<int> PRINTED_TIMES { get; set; }
        public Nullable<int> USED_TIMES { get; set; }
        public Nullable<int> MAXUSAGETIME { get; set; }
        public string HN { get; set; }
        public string PATIENT_NAME { get; set; }
        public string PATIENT_LASTNAME { get; set; }
        public string PATIENT_GENDER { get; set; }
        public string STAFF_ID { get; set; }
        public string STAFF_NAME { get; set; }
        public string CHANNEL { get; set; }
        public string STATUS { get; set; }
        public string STATUS_REMARKS { get; set; }
        public string REFUND_METHOD { get; set; }
        public Nullable<System.DateTime> CREATED_DATETIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATETIME { get; set; }
        public string UPDATED_BY { get; set; }
        public bool DELETED { get; set; }
        public Nullable<System.DateTime> ApplyDateTime { get; set; }
        public Nullable<decimal> REFUND_AMOUNT { get; set; }
        public string RefundOtherMethod { get; set; }
        public string EVENTCODE { get; set; }
        public string EVENTNAME { get; set; }
    }
}
