//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECouponAPI.Models
{
    using System;

    public partial class MEMBER
    {
        public int ID { get; set; }
        public Nullable<int> MemberNo { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string LASTNAME { get; set; }
        public string PERSONAL_ID { get; set; }
        public string PASSPORT_ID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string HOME_TELNO { get; set; }
        public string MOBILENO { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string POSTCODE { get; set; }
        public string BILLINGNAME { get; set; }
        public string BILLING_ADDRESS1 { get; set; }
        public string BILLING_ADDRESS2 { get; set; }
        public string BILLING_POSTCODE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<bool> ENABLED { get; set; }
        public Nullable<System.DateTime> CREATED_DATETIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATETIME { get; set; }
        public string UPDATED_BY { get; set; }
        public string GENDER { get; set; }
        public bool DELETED { get; set; }
        public string CHANNEL { get; set; }
        public string StatusRemark { get; set; }
        public string PreferLangCode { get; set; }
        public Nullable<bool> CONFIRMED { get; set; }
        public string CONFIRMCODE { get; set; }
    }
}
